# Generated by Django 3.2.13 on 2022-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0004_auto_20220518_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesetup',
            name='alertTemp2',
        ),
        migrations.AddField(
            model_name='node',
            name='vibraX2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='eixo x 2'),
        ),
        migrations.AddField(
            model_name='node',
            name='vibraZ2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='eixo z 2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='addrVibraX2',
            field=models.IntegerField(default=1, verbose_name='endereço eixo x 2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='addrVibraZ2',
            field=models.IntegerField(default=1, verbose_name='endereço eixo z 2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertTempNv2',
            field=models.DecimalField(decimal_places=1, default=70.0, max_digits=12, verbose_name='Alert Temperatura nv2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertVibraX2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert eixo x 2 - nv2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertVibraXNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert eixo x 1 - nv2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertVibraZ2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert eixo z 2 - nv2'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertVibraZNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert eixo z 1 - nv2'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraX',
            field=models.IntegerField(default=1, verbose_name='endereço eixo x 1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraZ',
            field=models.IntegerField(default=1, verbose_name='endereço eixo z 1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertTemp',
            field=models.DecimalField(decimal_places=1, default=50.0, max_digits=12, verbose_name='Alert Temperatura nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraX',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert eixo x 1 - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraX2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert eixo x 2 - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZ',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert eixo z 1 - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZ2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert eixo z 2 - nv1'),
        ),
    ]
