# Generated by Django 3.1 on 2022-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0005_auto_20220518_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist',
            name='alertTempNv2',
            field=models.DecimalField(decimal_places=1, default=70.0, max_digits=12, verbose_name='Alert Temperatura nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraX2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Acele - nv1'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraX2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Acele - nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraXNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Veloc - nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraZ2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Acele - nv1'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraZ2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Acele - nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertVibraZNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Veloc - nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='vibraX2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Acele Pico'),
        ),
        migrations.AddField(
            model_name='hist',
            name='vibraZ2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Acele Pico'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='alertTemp',
            field=models.DecimalField(decimal_places=1, default=50.0, max_digits=12, verbose_name='Alert Temperatura nv1'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='alertVibraX',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Veloc - nv1'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='alertVibraZ',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Veloc - nv1'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='vibraX',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='vibraZ',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='vibraX',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='node',
            name='vibraX2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='X Acele Pico'),
        ),
        migrations.AlterField(
            model_name='node',
            name='vibraZ',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='node',
            name='vibraZ2',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Z Acele Pico'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraX',
            field=models.IntegerField(default=1, verbose_name='endereço X Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraX2',
            field=models.IntegerField(default=1, verbose_name='endereço X Acele Pico'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraZ',
            field=models.IntegerField(default=1, verbose_name='endereço Z Veloc RMS'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='addrVibraZ2',
            field=models.IntegerField(default=1, verbose_name='endereço Z Acele Pico'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraX',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Veloc - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraX2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert X Acele - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraX2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Acele - nv2'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraXNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert X Veloc - nv2'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZ',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Veloc - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZ2',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=12, verbose_name='Alert Z Acele - nv1'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZ2Nv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Acele - nv2'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='alertVibraZNv2',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=12, verbose_name='Alert Z Veloc - nv2'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
