# Generated by Django 4.1.2 on 2023-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtx', '0006_auto_20220519_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='hist',
            name='alertCorrente',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Alert Corrente nv1'),
        ),
        migrations.AddField(
            model_name='hist',
            name='alertCorrenteNv2',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12, verbose_name='Alert Corrente nv2'),
        ),
        migrations.AddField(
            model_name='hist',
            name='corrente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Corrente'),
        ),
        migrations.AddField(
            model_name='node',
            name='corrente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Corrente'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='addrCorrente',
            field=models.IntegerField(default=1, verbose_name='endereço Corrente'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertCorrente',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12, verbose_name='Alert Corrente nv1'),
        ),
        migrations.AddField(
            model_name='nodesetup',
            name='alertCorrenteNv2',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=12, verbose_name='Alert Corrente nv2'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nodesetup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
